### ISSUE TITLE
docs: readme: update list of binaries

### ISSUE THREAD

**Issue by kamilsk** [octolab/homebrew-tap#4]
To do

- [x] remove/comment not actual
- [x] add new if present
- [x] refresh examples

**Comment by kamilsk** [comment]
related to kamilsk/homebrew-tap/issues/9

**Comment by kamilsk** [comment]
see https://github.com/1Password/homebrew-tap

**Comment by kamilsk** [comment]
- [ ] kamilsk/godownloader/issues/50
- [ ] kamilsk/go-tools/issues/27
- [ ] kamilsk/golangci-lint/issues/105
- [ ] kamilsk/dotfiles/issues/602

**Comment by kamilsk** [comment]
fixed
